site_name: ASPIRE
site_description: Documentation ASPIRE

repo_url: "https://github.com/theoelsti/ASPIRE"
edit_uri: "https://github.com/theoelsti/aspireDoc/edit/main/docs/"

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.tabbed:
      alternate_style: true 


plugins:
  - search
  - git-revision-date

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - toc.integrate


extra_css:
  - stylesheets/extra.css

nav:
    - "Index": 'index.md'
    - 'install.md'

    - 'Guides':
        - "Classes": 'install/#adding-an-admin'
          - "Principales"
          - "Capteurs"
          - "Layouts"
          
    - 'Gestion des erreurs':
      - 'troubleshooting.md'
  
